services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    user: root
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - surrealdb_data:/mydata
    command: start --log debug --user root --pass root surrealkv:/mydata/database.db
    restart: unless-stopped

volumes:
  surrealdb_data:
